ELELAB/cancermuts

- cancermuts/datasources.py
> adds automatic retrieval of ids

- cancermuts/datasources.py
> fixes metadata dependencies in cBioPortal

- cancermuts/datasources.py
> added default alias for property retrieval in ELM

- cancermuts/datasources.py
> adds better handling of NANs in gnomAD frequencies

- cancermuts/datasources.py
> fixes capitalization of file names that are sought after by Phosphosite

- cancermuts/table.py
> adds function to plot mobiDB structure

- cancermuts/table.py
> adds dtype switch for REVEL when plotting

- cancermuts/datasources.py
> handled condition in which we cannot find a mobidb prediction

- cancermuts/datasources.py
> switches cBioPortal data fetching from multiple GET to single POST

- cancermuts/core.py
- cancermuts/metadata.py
- cancermuts/properties.py
- cancermuts/table.py
fixes #143 
* implements header definition independent from description
* adds custom headers
> Changes table headers to be more computer-friendly

- cancermuts/table.py
> resorts columns so that reference and alternate amino acids are in the first columns

- cancermuts/table.py
> Replaces `numpy` type aliases with Python types

- cancermuts/datasources.py
- cancermuts/metadata.py
> Fixes handling of genes on X and Y chromosomes

- cancermuts/datasources.py
> Improves handling of gnomAD corner case in which no variant for gene is found

- cancermuts/datasources.py
- cancermuts/properties.py
fixes #147. Includes the ELM id in the metatable
> ELM accession number to metatable

- cancermuts/properties.py
- cancermuts/table.py
> Fixes ELM support for plotting

- cancermuts/datasources.py
> COSMIC crash with unsupported metadata

- cancermuts/datasources.py
- docs/tutorial.md
fixes #158. Simple first draft. Might also need changes in `def add_position_properties` and `def _get_mobidb_disorder_predictions`
> MobiDB API switch

- cancermuts/datasources.py
> Changed default 'exclude_elm_classes'

- cancermuts/datasources.py
- docs/tutorial.md
> Check for cosmic database file

- cancermuts/datasources.py
> Changed download and annotation of Uniprot ID/AC

- cancermuts/table.py
> improves compatibility with plotting for partial metatables

- README.md
> Adds mention to the Cancermuts web server to the README file

- cancermuts/table.py
> fixes handling of ELM descriptions with comma

- cancermuts/datasources.py
- cancermuts/metadata.py
> Replaces assertions when converting genomic coordinates

- cancermuts/datasources.py
> Improves handling of cases in which Entrez ID is not found

- cancermuts/datasources.py
> Fix handling of multiple entrez IDs, log warning

- cancermuts/datasources.py
> Shorten MyVariant code

- cancermuts/datasources.py
- docs/tutorial_alternative_isoforms.py
fix sub issue #213 from #43 adding safeguard for MOBIdb class in `datasources.py` and updating `tutorial_alternative_isoforms.py`
> Adding safeguard + update tutorial for MOBIdb class
